name: Hello World

on: 
  workflow_dispatch: 
  # push:
  #   #branches:
  #   # - main
  # schedule:
  #   - cron: "*/1 * * * *" 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: this is my step
       run: echo 'hello world Iulian'

     - name : another task
       run: echo "This is another run"
