name: Hello World

on: 
  workflow_dispatch: 
  # push:
  #   #branches:
  #   # - main
  # schedule:
  #   - cron: "*/1 * * * *" 
  pull_request:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: this is my step
       run: echo 'hello world Iulian'

     - name : another task
       run: echo "This is another run"
       
     - name: Checkout
       uses: actions/checkout@v6.0.2

     - name: List the files of the repo
       run: |
         echo "The repository  ${{github.repository}} contains the following files:"
         tree
         
     - name: Shows the contents of the new file
       run: cat new-file.txt 
     
      
