name : manual trigger

on: 
  workflow_dispatch:
    inputs:
      text:
        description: Label of a text field
        required: true
      build:
        description: build the 
        type: choice
        default: release
        options:
          - debug
          - release
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displayin 
        run: |
          echo "Label: ${{inputs.text.description}}"
      
    
        
     
        
    
  
